root = "."

[build]
cmd = 'go build -o /tmp/street.exe'
bin = '/tmp/street.exe'
full_bin = '/tmp/street.exe web'
include_ext = ['go']
exclude_regex = ['_test.go']
exclude_dir = ['backup', 'svelte' 'tmp']