name: Build and Test
'on':
  workflow_dispatch: null
  pull_request:
    branches:
      - master
jobs:
  Go-Build:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
      - run: |
          make setup
          go build -v ./...
          
  Go-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v4
      - run: |
          make setup
          go test -v ./...    
          
  Svelte-Test:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          node build.js
 
           
